language: python
python:
  - "3.3"
  - "3.4"
before_script:
  - wget -q -O - http://pkg.jenkins-ci.org/debian-stable/jenkins-ci.org.key | sudo apt-key add -
  - sudo sh -c 'echo deb http://pkg.jenkins-ci.org/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
  - sudo apt-get update -qq && sudo apt-get install -y jenkins
script: wget --spider --tries=10 --retry-connrefused --wait=4.2 http://localhost:8080 && nosetests test --verbose
notifications:
  email: false