language: python
python:
  - "3.3"
  - "3.4"
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libxml2-dev libxslt1-dev lib32z1-dev
before_script:
  - wget -q -O - http://pkg.jenkins-ci.org/debian-stable/jenkins-ci.org.key | sudo apt-key add -
  - sudo sh -c 'echo deb http://pkg.jenkins-ci.org/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
  - sudo apt-get update -qq
  - sudo apt-get install -y jenkins
  - python test/wait.py
  - sudo su jenkins -c !source
  - sudo su jenkins -c 'pip install lxml'
script: sudo su jenkins -c 'nosetests test --verbose'
notifications:
  email: false
